name: release
on:
  release:
    types: [ published ]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: installing JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - id: get-version
        run: |
          echo "version=$(echo $(basename ${{github.ref}}))" >> $GITHUB_OUTPUT
      - name: 'run jib'
        shell: bash
        run: |
          mvn versions:set -DnewVersion=${{ steps.get-version.outputs.version }}
          mvn install \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.REPO_TOKEN }}